site_name: Python RBAC Docs

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    primary: teal
    scheme: slate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            docstring_style: numpy
            members_order: source
            show_root_heading: true
            show_source: false

nav:
  - README: readme_symlink.md
  - Guide:
      - Start: guide/index.md
  - Comparison to ANSI: ansi.md
  - API Reference:
      - RBAC: api/rbac.md
      - Role service: api/role.md
      - Subject service: api/subject.md
      - Policy service: api/policy.md
      - Models: api/models.md
