site_name: PyPermission - RBAC for Python with SQLAlchemy
repo_url: https://gitlab.com/DigonIO/pypermission
repo_name: DigonIO/pypermission
copyright: Copyright Â© 2025 Jendrik Potyka & Fabian Preiss

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: teal
    scheme: slate
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature_annotations: true
            docstring_style: numpy
            members_order: source
            show_root_heading: true
            show_source: false
  - coverage:
      page_path: coverage
      html_report_dir: htmlcov

nav:
  - README: index.md
  - Quick Start: quick_start.md
  - Definitions: definitions.md
  - Permission Design Guide: permission_design_guide.md
  - Implementation Guide:
      - Start: guide/index.md
  - Comparison to ANSI: ansi.md
  - Comparison to NIST: nist.md
  - FAQ: faq.md
  - API Reference:
      - RBAC: api/rbac.md
      - Role service: api/role.md
      - Subject service: api/subject.md
      - Models: api/models.md
      - Util: api/util.md
  - Coverage Report: coverage.md

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: custom
    url: matomo.digon.io
  footer_links:
    - text: "Imprint"
      href: "https://digon.io/en/impress"
    - text: "Privacy Policy"
      href: "https://digon.io/en/privacy"
  social:
    - link: https://gitlab.com/DigonIO/pypermission
      icon: fontawesome/brands/gitlab
    - link: https://github.com/DigonIO/pypermission
      icon: fontawesome/brands/github

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
